### ISSUE TITLE
expo 에서 실행시 dark mode 미적용 

### ISSUE THREAD

**Issue by kimmoonil** [kimmoonil/moovies2#1]
![IMG_8280](https://user-images.githubusercontent.com/26863276/144360576-632b179b-ecd2-42f2-b35c-fb777c33a9c3.PNG)
![IMG_8278](https://user-images.githubusercontent.com/26863276/144360603-17852b3f-9b60-44da-9438-724d1f9219a0.PNG)

휴대폰에서 다크모드가 설정되어있고 , expo도 다크모드로 열림.

![IMG_8279](https://user-images.githubusercontent.com/26863276/144360596-dbe66323-a821-43cf-b937-405a07255a4e.PNG)

어플은 다크모드로 열리지 않음.

<img width="1680" alt="스크린샷 2021-12-02 오후 1 50 07" src="https://user-images.githubusercontent.com/26863276/144360695-59669ad7-943a-4512-900e-66966a74585b.png">

하지만 동일한 코드로 시뮬레이터에서는 다크모드가 잘 작동됨..

**Comment by serranoarevalo** [comment]
Add this:

```json
{
  "expo": {
    "userInterfaceStyle": "automatic"
  }
}
```

To your app.json

Also, please open issues on our website and not on Github so other people can answer or get help.

💖
